### ISSUE TITLE
Allow running silently (no `console.log`)

### ISSUE THREAD

**Issue by steveadams** [evanwashere/mitata#16]
Thanks for such a great benchmarking library.

I've been using the data returned from `run` to get what I want from benchmarks, but mitata still writes to `console.log`. Would it be possible, or within the project's intended use cases, to allow for silent runs in which `console.log` is not called?

In my use case, I collect reports and output data about them to stdout conditionally. However, mitata outputs to stdout unconditionally. If I was writing my data to disk this would be totally fine; I could pipe mitata's outputs into a void and ignore it. However, I specifically want to see my outputs in stdout, and the use of `console.log` within mitata is polluting it.

If this would be a welcome change, I'd be happy to put together a pull request to make this happen. Apologies if there's a way to get around this issue and I've failed to figure it out; I'm vey open to suggestions.

**Comment by evanwashere** [comment]
added silent option to 0.1.7
