### ISSUE TITLE
Feature: ability to set the number of repetitions

### ISSUE THREAD

**Issue by reserved-word** [evanwashere/mitata#17]
At the current moment I get unstable results that depend among other things on the order in which the benches are run, it would be useful to be able to increase the number of repetitions to increase the accuracy of the measurement.

Thank you

**Comment by evanwashere** [comment]
order issue is fixed in 0.1.7, option to set iterations will be added in 1.0.0

**Comment by wottpal** [comment]
Would love to set iterations as well!

**Comment by wottpal** [comment]
Yeah I have one localhost API call involved (which is super hard to mock because it's called by some internal library) which fluctuates a bit and therefore I would love to increase the amount of runs.

**Comment by evanwashere** [comment]
you can now fully customize benchmark loop in 1.0.0 with building blocks
