### ISSUE TITLE
Feature: provide an option to calculate ops

### ISSUE THREAD

**Issue by gwsbhqt** [evanwashere/mitata#20]
Small units of time like picoseconds, nanoseconds, microsecond etc don't seem very intuitive. It would be better if provide operations per second.

**Comment by evanwashere** [comment]
I think it's the opposite. seeing the time allows to easily deduce a lot of things like function being completely optimized out when iteration only takes picoseconds.
the only issue i have encountered is that not everyone knows their si units (usually their knowledge stops at milliseconds)

i recommend watching this video https://youtu.be/9eyFDBPk4Yw and rethinking usage of abstract units like ops/s

(you can always divide 1s by avg iteration time to get your ops/s)
