### ISSUE TITLE
Can you provide some release changelog?

### ISSUE THREAD

**Issue by JounQin** [evanwashere/mitata#22]

**Comment by evanwashere** [comment]
commit description contains summary of changes
<img width="922" alt="image" src="https://github.com/evanwashere/mitata/assets/70155278/53763761-926d-4476-b3ec-4735ba0f5bb7">

**Comment by JounQin** [comment]
It could be, but not quite useful when other tools like @renovatebot raising related PR like https://github.com/un-ts/sh-syntax/pull/91#issue-comment-box

<img width="931" alt="image" src="https://github.com/evanwashere/mitata/assets/8336744/4f06524d-f671-4c96-aa2c-f9014d794652">

**Comment by evanwashere** [comment]
that's tool's problem, not every library depends on having github releases or even being on github at all

**Comment by JounQin** [comment]
I understand your position, but in another view, release/changelog are easier to read vs commit messages, aren't they?

**Comment by evanwashere** [comment]
for large projects it's definitely useful but for my tiny projects i prefer quick push & publish

**Comment by tabarra** [comment]
@evanwashere I appreciate your work, even for "tiny projects", but I do recommend you getting a github action set up that will do the entire build & publish for you, it will write the changelog as the description of your GH release.  
Bonus point if it has included attestation & npm publishing, as supply chain attacks are getting more common by the day.
