### ISSUE TITLE
Output format compliant with Deno.bench or BMF JSON

### ISSUE THREAD

**Issue by jerome-benoit** [evanwashere/mitata#24]
Would it be possible to align the output format with the Deno.bench() or BMF JSON? 

I think currently the column `iter/s` is missing. 

BMF JSON support would allow tools like bencher to parse it without needing much portability and maintenance effort between JS runtime.

**Comment by evanwashere** [comment]
`Deno.bench()` does look similar (I created it) but other than that it's its own format that follows Deno's needs and not mine

there are plans for matching json output of google/benchmark (part of 1.0.0 and `bun bench` command)

**Comment by jerome-benoit** [comment]
Implemented in tatami-ng: https://github.com/poolifier/tatami-ng
