### ISSUE TITLE
Usage of colors in bench names breaks rendering.

### ISSUE THREAD

**Issue by arthurfiorette** [evanwashere/mitata#32]
In one of my use cases, i would like to use ansi color codes to differentiate 2 benchs that are different, but there for basic comparison, using colors breaks output:

![image](https://github.com/user-attachments/assets/50f93cfe-d083-4b62-bbcc-e9db6bfa00fa)

**Comment by evanwashere** [comment]
names have to be clean (lineplot for example adds its own highlight to names) but I can add `bench().highlight(color)` similar to `.compact()`

**Comment by evanwashere** [comment]
you can now highlight names using `.highlight(color)` or `.name(name, color)` in ^1.0.11, it currently doesn't propegate to charts (will be added later)
