### ISSUE TITLE
Hardware Counters for Windows

### ISSUE THREAD

**Issue by aqilc** [evanwashere/mitata#41]
Windows provides many APIs for performance measurement, some examples below:

https://learn.microsoft.com/en-us/windows/win32/perfctrs/using-the-perflib-functions-to-consume-counter-data
https://learn.microsoft.com/en-us/windows/win32/perfctrs/using-the-pdh-functions-to-consume-counter-data

You can also query many of the counters through assembly. I really hope this can be a feature that can be used on something like Bun for Windows!

**Comment by evanwashere** [comment]
likely won't get added as I don't use windows in any capacity, so it's not something I can easily continuously test and maintain (not including all the work required to test across different cpus). building the native napi library side for windows is also more convoluted.

**Comment by aqilc** [comment]
Yeah Windows is a pain, so it's understandable. Thank you for taking it into consideration though and I love using this library so much for all my benchmarks! Have a great New Years!! 🎉🎄🎁
