### ISSUE TITLE
Process completed with exit code 137

### ISSUE THREAD

**Issue by JounQin** [evanwashere/mitata#5]
https://github.com/rx-ts/sh-syntax/pull/32

https://github.com/rx-ts/sh-syntax/runs/7027658734?check_suite_focus=true

**Comment by JounQin** [comment]
@evanwashere 

> Thanks for the quick answer, maybe the limitation should be documented. I searched the README file, but could not find any reference about it.

**Comment by evanwashere** [comment]
> @evanwashere
> 
> > Thanks for the quick answer, maybe the limitation should be documented. I searched the README file, but could not find any reference about it.

fixed in 0.1.6, mitata now will check for promises during warmup and switch to async logic if required
