### ISSUE TITLE
Clarify node versions support? And Node 14?

### ISSUE THREAD

**Issue by JounQin** [evanwashere/mitata#6]
```log
file:///home/runner/work/yocto-ttl-cache/yocto-ttl-cache/node_modules/.pnpm/mitata@0.1.6/node_modules/mitata/src/cli.mjs:178
  const colors = opts.colors ??= true;
                             ^^^
SyntaxError: Unexpected token '??='
    at Loader.moduleStrategy (internal/modules/esm/translators.js:145:1[8](https://github.com/un-ts/yocto-ttl-cache/runs/7299432226?check_suite_focus=true#step:7:9))
Error: Process completed with exit code 1.
```

**Comment by xHyroM** [comment]
> ```
> file:///home/runner/work/yocto-ttl-cache/yocto-ttl-cache/node_modules/.pnpm/mitata@0.1.6/node_modules/mitata/src/cli.mjs:178
>   const colors = opts.colors ??= true;
>                              ^^^
> SyntaxError: Unexpected token '??='
>     at Loader.moduleStrategy (internal/modules/esm/translators.js:145:1[8](https://github.com/un-ts/yocto-ttl-cache/runs/7299432226?check_suite_focus=true#step:7:9))
> Error: Process completed with exit code 1.
> ```

You need have nodejs 15> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_nullish_assignment

**Comment by JounQin** [comment]
I understand that, but there is no `engines#node` field in `package.json` which makes it confusing.

**Comment by JounQin** [comment]
Friendly pin @xHyroM 

If you agree, I want to raise a PR for it.

**Comment by evanwashere** [comment]
v14 is not supported anymore and I encourage people always to try to use more up to date versions of engines and runtimes
