### ISSUE TITLE
Compare two benchmark outputs

### ISSUE THREAD

**Issue by xHyroM** [evanwashere/mitata#7]
It would be useful if it could be set to automatically save the output of the benchmark (e.g. to .json) and then the two could be automatically compared to produce something like this:
![image](https://user-images.githubusercontent.com/56601352/179233662-3ab8cf6a-e6e4-49cd-afb8-03a601b21876.png)

I made simple script:
```js
import { summary } from 'mitata/reporter/table.mjs';
import { join } from 'node:path';

const __dirname = new URL('.', import.meta.url).pathname;

const outputBunUtilities = JSON.parse(await (await Bun.file(join(__dirname, 'outputs', 'bun-utilities.json'))).text()).benchmarks.map(b => {
    return { ...b, name: `[bun-utilities] ${b.name}`, id: b.name };
});
const outputNodeChildProcess = JSON.parse(await (await Bun.file(join(__dirname, 'outputs', 'node-fs.json'))).text()).benchmarks.map(b => {
    return { ...b, name: `[node-fs] ${b.name}`, id: b.name };
});

const benchmarks = [].concat(outputBunUtilities, outputNodeChildProcess);
const summaries = [
    'copydir empty',
    'copydir files',
    'rmdir empty',
    'rmdir files'
];

for (const summaryName of summaries) {
    const filtered = benchmarks.filter(b => b.id === summaryName);
    console.log(summary(filtered));
}
```

![image](https://user-images.githubusercontent.com/56601352/179237473-3a105b3f-3ba2-4753-8304-336ebc503159.png)

**Comment by evanwashere** [comment]
that's a job for another tool, mitata tries to be lean and support every possible engine and runtime without changes (this includes not depending on fs)

**Comment by slavensusic1** [comment]
hello, what i the recomended tool to use for comparison?
